### PR TITLE
Update to SymbolicUtils v0.10

### PR DESCRIPTION
**Pull request by YingboMa**

### CODE REVIEW

**Review by isaacsas — APPROVED** [review]

**Comment by isaacsas** [comment]
LGTM. How does one construct parameters or variables from strings/symbols now?

**Comment by YingboMa** [comment]
Yeah... I will need to add that `@variables $x` thingy.

**Comment by isaacsas** [comment]
OK, cool. I need that feature for `ReactionNetworkImporters` to generate variables/symbols from the network files it loads.

**Comment by shashi** [comment]
You can call `toparam` on a variable.

**Pull request merged**
