### PR TITLE
Try reenabling PETab tutorial

### PR DESCRIPTION
**Pull request by isaacsas**
It would be nice to get this back into the docs.

### CODE REVIEW

**Comment by isaacsas** [comment]
@sebapersson should PETab work with the latest Catalyst and MTK now?

**Comment by isaacsas** [comment]
Ahh, I see PEtab doesn't support the latest optimization yet which we've updated to, so this isn't going to work.

**Comment by isaacsas** [comment]
Awesome, let us know and we will reenable as soon as a release that works with the bumped optimizations libs is out.

**Comment by ChrisRackauckas** [comment]
If you're not using the data iterator or the extra cost function argument results it should just be a quick bump. I have a few tutorial bumps to look into (DiffEqFlux, SciMLSensitivty), but they've now made it to the top of my inbox so if you need help, see those PRs from Vaibhav before I get the merge.

**Pull request closed without merging**
