### PR TITLE
Test on 1.9 instead of 1.6

### PR DESCRIPTION
**Pull request by TorkelE**

### CODE REVIEW

**Comment by isaacsas** [comment]
If everything passes feel free to merge.

**Review by isaacsas — APPROVED** [review]

**Comment by isaacsas** [comment]
Oh, you also need to update Julia to 1.9 in the Project.toml.

**Comment by TorkelE** [comment]
Yeah, I am not sure if it is related to https://github.com/SciML/Catalyst.jl/pull/728, Avik said that looked strange

**Comment by isaacsas** [comment]
The error comes from the first let block in the nonlinear solve tests. If I manually run that code I get the error, but then if I rerun it everything works fine.

**Comment by TorkelE** [comment]
Just running the block on my computer it is fine, and https://github.com/SciML/Catalyst.jl/pull/721 passed as well. I still think it must have been something with that compact update that was added in.

**Comment by TorkelE** [comment]
The only otehr alternatvie I can come up with is that StableRNGs have started generating some other rnd number, and this one somehow is problmatic.

**Comment by TorkelE** [comment]
Ok, I had another chat with Avik, we now have a test that NonlinearSolve should solve stabily.

**Comment by isaacsas** [comment]
Great, maybe just make the changes in this PR? Then we can merge this and hopefully get CI fixed.

**Comment by TorkelE** [comment]
done, yeah, hopefully, this shoudl settle things. Should I try rebase the other PRs (that currently fail 1.6) on master afterwards?

**Comment by isaacsas** [comment]
Yes, start updating your PRs as we merge stuff in.

**Pull request merged**
