### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by spaette**
@isaacsas 

there may be other grammatical errors throughout the repo

### CODE REVIEW

**Review by TorkelE — APPROVED** [review]

**Comment by isaacsas** [comment]
@TorkelE please feel free to handle merging this one. (But right now tests are failing?)

**Comment by TorkelE** [comment]
Will handle this, the tests and some doc fixes larer today, hopefully it will be straightforward

**Comment by spaette** [comment]
my mention of grammatical errors was solely based on my having noticed in the patch the following

where the author's intention may have been `these conversions` and `all differentials will`

```
$ sed -n '593p' /tmp/Catalyst.jl/src/reactionsystem_conversions.jl
                If you still would like to perform this conversions, please use the `all_differentials_permitted = true` option. In this case, all differential will be set to `0`. 
$ 
```

**Comment by TorkelE** [comment]
Thanks! I will update that as well

**Pull request merged**
