### PR TITLE
Add compatibility with more recent versions of mtk

### PR DESCRIPTION
**Pull request by ctessum**
## Checklist

- [ ] Appropriate tests were added
- [ ] Any code changes were done in a way that does not break public API
- [ ] All documentation related to code changes were updated
- [ ] The new code follows the
  [contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
  [COLPRAC](https://github.com/SciML/COLPRAC).
- [ ] Any new documentation only uses public API

### CODE REVIEW

**Comment by isaacsas** [comment]
These aren't breaking releases, so why does this require a PR?

**Comment by isaacsas** [comment]
Note that we can't release a version with Symbolic 6 support till our CI is passing again. Hopefully the MTK unit PR I just submitted fixes things, but we need a new MTK release to test against.

**Comment by isaacsas** [comment]
I'm going to close this. Once the new MTK release is available I will get https://github.com/SciML/Catalyst.jl/pull/961 merged (assuming tests pass), and then make a new release. That should add support for newer MTK versions.

Thanks for the PR in either case though!

**Comment by isaacsas** [comment]
Catalyst 14.4 should be released shortly and compatible with recent MTK versions.

**Comment by ctessum** [comment]
Got it, thanks!

**Pull request closed without merging**
