### PR TITLE
Update test extensions Project.toml

### PR DESCRIPTION
**Pull request by isaacsas**

### CODE REVIEW

**Comment by isaacsas** [comment]
@ChrisRackauckas new NonlinearSolve related CI error we are getting suddenly: https://github.com/SciML/Catalyst.jl/actions/runs/12012076797/job/33482494159?pr=1136#step:7:20

**Comment by isaacsas** [comment]
I'm going to merge this as the doc issue seems unrelated (it just popped up and seems NonlinearSolve or SciMLBase related).

**Comment by ChrisRackauckas** [comment]
It doesn't seem related to either? It seems like it's a Cassette.jl bug in v1.11.1? 

@oscardssmith does that look like it has a quick fix? Looks like it's maybe memory related.

**Comment by oscardssmith** [comment]
possibly? I don't know the cassette codebase that well. @aviatesk might have know better (but if not, I'll take a look)

**Pull request merged**
