### PR TITLE
New UUID for name change

### PR DESCRIPTION
**Pull request by ChrisRackauckas**

### CODE REVIEW

**Comment by isaacsas** [comment]
I think we need to take another look at our tests — they seem to be prone to intermittent failures for some reason. A mix of inconsistency with the results in obtaining the requested accuracy, and perhaps the shear memory size of the many networks that are loaded?

**Comment by TorkelE** [comment]
Which one failed this time?

**Comment by isaacsas** [comment]
The SDE tests.

**Comment by isaacsas** [comment]
But there was no info on where the failure occurred in the file that I saw on quick glance. The crash was in general stdlib code supposedly.

**Comment by isaacsas** [comment]
Actually it looks like it finished SDEs but crashed before printing anything for jumps.

**Comment by TorkelE** [comment]
Ok, that's weird. Yes, those should be fine.

**Pull request merged**
