### PR TITLE
Add bif tutorial

### PR DESCRIPTION
**Pull request by TorkelE**
Adds a tutorial for creating bifurcation diagrams to the docs.

### CODE REVIEW

**Comment by TorkelE** [comment]
Is there a way to preview the doc changes to see if they turned out as intended? Probably everything should be fine.

**Comment by ChrisRackauckas** [comment]
>Is there a way to preview the doc changes to see if they turned out as intended? Probably everything should be fine.

We could install a bot for that, but 🤷 I usually do the janky method of try and repeat.

**Comment by ChrisRackauckas** [comment]
There's no link to the page added in the docs in this PR, so it won't show up. But you can manually go to the page to see.

**Comment by TorkelE** [comment]
> > Is there a way to preview the doc changes to see if they turned out as intended? Probably everything should be fine.
> 
> We could install a bot for that, but  I usually do the janky method of try and repeat.

Sometimes the more blunt solutions are the easier ones. Will fix the link though.

**Pull request merged**
