### PR TITLE
Add errors for array species/parameters when submitted to `LatticeReactionSystem`s

### PR DESCRIPTION
**Pull request by TorkelE**
Long-term we should probably support it. However, doing so will be a decent chunk of work, and rather low priority right now.

### CODE REVIEW

**Comment by isaacsas** [comment]
I think we need to drop GLMakie in docs and tests. It just is too unreliable.

**Comment by isaacsas** [comment]
@jonathanfischer97 we are getting GLMakie issues again. Any suggestions?

**Review by isaacsas — APPROVED** [review]

**Comment by isaacsas** [comment]
Feel free to merge as the doc failures are unrelated.

**Comment by jonathanfischer97** [comment]
Sorry for missing this guys. Indeed, it seems that GFLW load issue just won't go away, shame. 

I'll look into it when I get some time, but let's just drop it for now until I find a fix or GLMakie itself is more mature.

**Pull request merged**
