### PR TITLE
ModelingToolkit unit validation logic

### PR DESCRIPTION
**Pull request by lamorton**
This will be necessary (in order to take advantage of unit validation) when [ModelingToolkit.jl#1156](https://github.com/SciML/ModelingToolkit.jl/pull/1156#) lands.

### CODE REVIEW

**Review by ChrisRackauckas — APPROVED** [review]

**Comment by isaacsas** [comment]
Do we need to add the validation check in the ReactionSystem constructor too? (I noticed it in your MT PR, but that lives here now.)

**Comment by lamorton** [comment]
> 
> 
> Do we need to add the validation check in the ReactionSystem constructor too? (I noticed it in your MT PR, but that lives here now.)

Yup, just pushed it.

**Comment by isaacsas** [comment]
Could you propagate the checks keyword to the outer constructors too so users can use it easily?

**Comment by isaacsas** [comment]
Looks great. Thanks for all the effort with adding in unit support!

**Pull request merged**
