### PR TITLE
Petab tutorial

### PR DESCRIPTION
**Pull request by TorkelE**
Creates a tutorial on how to use PEtab (https://github.com/sebapersson/PEtab.jl/) to fit the parameters of ODE CRNs to data (adapted from that documentation to provide a shorter summary to get someone started).

What is currently missing:
1) Plots to evaluate optimisation runs are not complete yet (https://github.com/sebapersson/PEtab.jl/pull/83). When that is done, I will complete that tutorial.
2) The `get_best_ps` function is not yet implemented in PEtab (but hopefully will be soon https://github.com/sebapersson/PEtab.jl/pull/85).
3) PEtab does not currently support events, so that section will be empty until it does.
4) It is possible to have different parameters for different experimental/simulation conditions. I started a tutorial for this, but haven't completed it yet (still figuring out the best way to do this).

### CODE REVIEW

**Comment by TorkelE** [comment]
This includes some new stuff, so the documentary will fail until PEtab 2.0 is released.

**Comment by TorkelE** [comment]
This tutorial is now in a good state where I am happy to receive feedback before merging.

A side note (and a problem) is that I am unable to update the Project.toml file in the docs environment to use the latest PEtab version (2+). I get this error:
```
(docs) pkg> update PEtab
    Updating registry at `~/.julia/registries/General.toml`
ERROR: Unsatisfiable requirements detected for package SuiteSparse_jll [bea87d4a]:
 SuiteSparse_jll [bea87d4a] log:
 ├─possible versions are: 7.2.0 or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions: 7.2.0
 └─found to have no compatible versions left with Sundials_jll [fb77eaff]
   └─Sundials_jll [fb77eaff] log:
     ├─possible versions are: 3.1.1-6.6.0 or uninstalled
     └─restricted to versions 5.2.1 by an explicit requirement, leaving only versions: 5.2.1
```
which does not directly seem to involve PEtab. Unsure how to interpret it, but I have had various weird package management errors relating to Sundials of late.

**Comment by isaacsas** [comment]
This needs to be updated to master so it doesn’t show all the recently merged code as new commits and just the new code is apparent.

**Comment by TorkelE** [comment]
I thought I did rebase it on master (and that's why the extra commits to do that appeared) but apparently something messed up. Trying again now. I think I'm just juggling so many different PRs, some with dependencies on each other, that it's getting really messy to keep track of now

**Comment by TorkelE** [comment]
I am not sure if that did things any better, but now ti should be on the master at lesat.

**Comment by isaacsas** [comment]
It is still showing a ton of merged and existing code as part of this PR.

**Comment by TorkelE** [comment]
When I try rebasing this on master it all shows up OK. I think Git have just gone bananas between this and other PRs, and most of these changes are just basically synching this with older stuff. I think the only work around would be to create a new PR.

**Comment by TorkelE** [comment]
Closed by https://github.com/SciML/Catalyst.jl/pull/701

**Pull request closed without merging**
