### PR TITLE
Stability computation

### PR DESCRIPTION
**Pull request by TorkelE**
No docs and tests, and internal needs to be improved to handle vector of values (not maps) input prettier, but functionality works. Enables computation of stability o steady states. Conservation laws should be accounted for (not tested yet).

Simple example:
```julia
using Catalyst
import HomotopyContinuation

rs = @reaction_network begin
    (v/10.0 + hill(X, v, K, n), d), 0 <--> X
end
p = [:v => 2.0, :K => 1.0, :n => 3, :d => 1.0]
steady_states = hc_steady_states(rs, p)

steady_state_stability(steady_states[1], rs, p) # true
steady_state_stability(steady_states[2], rs, p) # false
steady_state_stability(steady_states[3], rs, p) # true

steady_state_stability(steady_states, rs, p) # [1, 0, 1]

ss_jac = steady_state_jac(rs) # [1, 0, 1]
steady_state_stability(steady_states, rs, p; ss_jac=ss_jac) # [1, 0, 1]
```

### CODE REVIEW

**Comment by TorkelE** [comment]
No documentation, but internals and tests are there.

**Comment by TorkelE** [comment]
If checks everything passes, this should be ready for merging.

**Comment by isaacsas** [comment]
OK, I'll let you know once I've given it a review.

**Comment by TorkelE** [comment]
superseeded by https://github.com/SciML/Catalyst.jl/pull/739

**Pull request closed without merging**
