### PR TITLE
Netstoich api fun

### PR DESCRIPTION
**Pull request by isaacsas**

### CODE REVIEW

**Comment by isaacsas** [comment]
@YingboMa Do you have any idea about this test failure I'm getting in the doc test that says it is occurring in Symbolics? Thanks!

**Comment by YingboMa** [comment]
Umm, I am not sure. I cannot reproduce it locally.

**Comment by ChrisRackauckas** [comment]
https://github.com/SciML/Catalyst.jl/blob/master/.github/workflows/Documentation.yml#L17 make that just 1

**Comment by isaacsas** [comment]
Thanks! Wonder where I copied that from when I added it. Might need to update some other repositories too now...

**Comment by isaacsas** [comment]
@yewalenikhil65 Just FYI!

**Pull request merged**
