### PR TITLE
Add tests for NonlinearSolve and NonlinearProblem

### PR DESCRIPTION
**Pull request by TorkelE**
Currently, we do not really test the conversions to `NonlinearSystem`s and `NonlinearProblem`s and their solutions. We do some tests on `SteadyStateProblem`s, but these are kind of deprecated anyway.

This PR adds some tests to this. The tests should be good, but need to check whether the tolerances are not good enough that the outputs are close enough to 0. If not, I will have to make stuff more lenient.

### CODE REVIEW

**Comment by isaacsas** [comment]
`1e-18` is smaller than machine epsilon, so seems too stringent for tests to pass. Checking to a relative accuracy of `1e-8` for solutions that are order 1 in size would be fine I think.

**Comment by TorkelE** [comment]
Sounds like a better way, will do that and reduce tolerance to something sensible.

**Comment by TorkelE** [comment]
I had to disable the tests for 1.6 (still unclear why NonlinearSolve fails there, but it is already a problem we are having and I think that package might have stopped supporting 1.6 anyway).

Otherwise, this is ready and good to go.

**Comment by ChrisRackauckas** [comment]
> I had to disable the tests for 1.6 (still unclear why NonlinearSolve fails there, but it is already a problem we are having and I think that package might have stopped supporting 1.6 anyway).

Yes it already had to drop v1.6 because of certain compiler issues.

**Pull request merged**
