### PR TITLE
Update bifurcation_diagram.md

### PR DESCRIPTION
**Pull request by rveltz**
Minor change to respect BifurcationKit interface

### CODE REVIEW

**Comment by isaacsas** [comment]
Thanks! Just to double check, this runs on the latest release with these changes?

**Comment by rveltz** [comment]
yes

**Comment by rveltz** [comment]
This example is tough! The equations are badly conditioned. Where did you get it from?

**Comment by isaacsas** [comment]
@TorkelE came up with it, so perhaps he can give a citation.

**Comment by isaacsas** [comment]
Looks like some kind of gene regulatory model...

**Comment by TorkelE** [comment]
It is a generalised version of a gene regulation model, I made it some time ago. I include it here because you could have a Hopf and a Fold bifurcation in the same diagram. If you have any comments on it I'd be interested to hear though!

**Comment by rveltz** [comment]
The normal form of the Hopf has tiny coefficients, the period of the cycle is large (~900). Direct simulation near the hopf hints at a slow-fast system, see the homoclinic like orbit.... this is tough for BifurcationKit
Screen Shot 2022-01-12 at 21 27 29
t

**Comment by rveltz** [comment]
> If you have any comments on it I'd be interested to hear though!

I think to study it, you have to "unfold" the parameters, like perform continuation of the fold and Hopf. Do you have a paper where the parameters where taken?

**Comment by rveltz** [comment]
I can find a bogdanov-takens point nearby. I guess the homoclinic orbit comes from there.

**Comment by TorkelE** [comment]
Practically, with regards to the example in the docs, do you think it might be better to replace it with a normal bistable switch?

I have to admit I am a bit out of my depth here, I am neither familiar with homoclinic orbits nor bogdanov-takens points. Also, with "unfold" the parameters, do you mean that I take another parameter and track how the position of the bifurcation points change as I change that parameter? I have to admit, I was unaware of this technique until I got more familiar with BifurcationKit and its examples. I have never really seen it done in analysis, so have never really thought of doing it myself.

The parameter set is nothing (intentionally) special. It is simply one where I could generate both bifurcation points (and a bit similar to a set I had used for a nondimensionalised version of the system, with noise added).

**Pull request merged**
