### PR TITLE
MTK tests update

### PR DESCRIPTION
**Pull request by TorkelE**
Went through the MTK tests, fixed some things. Unfortunatelye everything major that was broken still is.

### CODE REVIEW

**Comment by isaacsas** [comment]
Feel free to merge if you are done and tests pass.

It might be good more generally to go through your various open issues on indexing and remake and collate them all into one, new, big issue in MTK? (Closing the old ones.) Just to give a bump on all this and to summarize where things stand today since that may not be clear to everyone.

**Comment by ChrisRackauckas** [comment]
Yes. My understanding is that everything is done, so I would expect most of your issues close? It looks like we missed one symbolic+array part that you just highlighted, but hopefully that's the only part that slipped.

**Comment by TorkelE** [comment]
Yeah, I think I will need to do another write-up with summaries. I think there might have been some issues that was partially solved, but some follow-up sub cases wasn't.

**Comment by TorkelE** [comment]
The test failure seems to be some form of regression on master. Present in other PRs that only affect docs as well.

**Comment by isaacsas** [comment]
@TorkelE should we merge this?

**Pull request merged**
