### PR TITLE
try to add PEtab back

### PR DESCRIPTION
**Pull request by isaacsas**

### CODE REVIEW

**Comment by isaacsas** [comment]
@TorkelE seemsmthe tutorial needs updating to work with the latest PEtab.

**Comment by sebapersson** [comment]
Something that might cause this issue is that with 3.0 I dropped on of the `PEtabModel` constructors. Specifically, `simulation_conditions` must always be provided as a keyword now:

```julia
PEtabModel(sys, observables, measurements, parameters; 
           simulation_conditions = simulation_conditions kwargs...)
```

More details on changed syntax can be found [here](https://github.com/sebapersson/PEtab.jl/blob/main/HISTORY.md)

**Comment by TorkelE** [comment]
I have been meaning to try and remake and improve this one a bit, but might not have time to make it properly for a few weeks. Will try to fix so that it builds properly though.

**Comment by sebapersson** [comment]
Thanks, happy to help if you encounter any problems!

**Comment by isaacsas** [comment]
I will close this for now since the tutorial needs updating, and whoever takes that on can open a new PR with their updates.

**Pull request closed without merging**
