### PR TITLE
General doc update

### PR DESCRIPTION
**Pull request by TorkelE**
Preparing for the PEtab doc update.
- Update the version of packages used for building docs.
- Updates the Bifurcation tutorial for v 0.3.
- Adds references at the bottom of certain doc pages (e.g. book on bifurcations at the bottom of the bifurcation tutorial).
- - Makes the coagulation tutorial use the same reference style (for stuff at the bottom) as other doc pages.

### CODE REVIEW

**Comment by isaacsas** [comment]
Looks like the doc build shows some errors in the homotopy contin tutorial?

**Comment by TorkelE** [comment]
Yes, redoing. I had someone show me how to build the docs locally as well, should hopefully make it easier to check for these kinds of stuff.

**Comment by TorkelE** [comment]
When I formated the references like this:
```
[^1]: [Yuri A. Kuznetsov, *Elements of Applied Bifurcation Theory*, Springer (2023).](https://link.springer.com/book/10.1007/978-3-031-22007-4)
```
(to achieve the same format as we used elsewhere)

I get some warnings:
```
┌ Warning: unused footnote named '1' in src/catalyst_applications/bifurcation_diagrams.md.
└ @ Documenter.DocChecks ~/.julia/packages/Documenter/bYYzK/src/Utilities/Utilities.jl:34
```
which should be fine (unless there is some secondary effect causing problems, e.g. the references at the bottom being removed). It looks fine in the local build though.

Everything else should work.

**Comment by isaacsas** [comment]
What about this error https://github.com/SciML/Catalyst.jl/actions/runs/6660372195/job/18101364156?pr=706#step:5:272

**Comment by TorkelE** [comment]
Yes, tehre was a link that didn't work, should be fixed now.

**Comment by isaacsas** [comment]
OK, if there are no more warnings/errors once the doc build finishes I'm happy for you to merge. (Ignoring the factorial warning from the MTK bug.)

**Comment by TorkelE** [comment]
Sorry. The doc build failed beacuse there were some stuff on master that wasn't here (the references to PEtab that I added directly. So I tried to reabse this on master. But that caused duplications where somehow this now marks having the same commits twice. Will try to figure out how to sort this out.

**Pull request merged**
