### PR TITLE
hillr to hillR

### PR DESCRIPTION
**Pull request by thompsonmj**
`hillr` changed to `hillR` to avoid error `UndefVarError: hillr not defined`

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Why the capital @isaacsas ?

**Comment by isaacsas** [comment]
IDK, blame @TorkelE :)

We could add a PR adding `hillr` and such too.

**Comment by ChrisRackauckas** [comment]
`hillr` would match the style standards, so I would prefer it.

**Comment by isaacsas** [comment]
So drop the current naming and have a breaking release? Or keep the docs as is but add back `hillr`?

**Comment by isaacsas** [comment]
i.e. remove `hillR` and such?

**Comment by TorkelE** [comment]
Yeah, seems `hillr` is not enabled. Totally could add that as well. Not sure why it didn't make it when I remade how the functions worked. Is there a reason we would want `hillR` actively removed? Otherwise I'll just make a PR add `hillr` in.

**Comment by TorkelE** [comment]
see https://github.com/SciML/Catalyst.jl/pull/353

**Comment by isaacsas** [comment]
@thompsonmj I'm going to close this since @TorkelE instead added in the lowercase function versions. Thanks for bringing this to our attention!

**Pull request closed without merging**
