### PR TITLE
Variables in DSL

### PR DESCRIPTION
**Pull request by isaacsas**
Closes https://github.com/SciML/Catalyst.jl/issues/615
Closes https://github.com/SciML/Catalyst.jl/issues/624

### CODE REVIEW

**Comment by isaacsas** [comment]
@TorkelE I think our PRs are basically the same, but I added tests and refactored a bit. So ok if I just merge this one?

**Comment by TorkelE** [comment]
Have to go to a meeting right now, is it OK if I check later in the evening? My main worry is that merging now will mess up the increasingly humongeous test update that should be finished by tomorrow anyway.

**Comment by TorkelE** [comment]
Things looks good, I will have the tests done by our meeting tomorrow.

**Comment by isaacsas** [comment]
@TorkelE I handled the `@ivs` macro here. So this should now finish it all off.

**Comment by TorkelE** [comment]
Sounds good, I am looking at fixing the test thing now

**Pull request merged**
